# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tarefa 8 - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Execução de testes
    - run: npm i
    - run: npm test

  build:
    runs-on: ubuntu-latest
    # needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    # Build de projeto
    - run: npm i
    - run: npm run build
    - run: cd dist
    - run: ls
    - run: tar -czvf ./../build.tar.gz ./
    - run: ls
    - run: cd ./..
    - run: ls


    # Upload do artefato de build
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./build.tar.gz
